[project]
name = "openghost"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy==1.26.4",
    "opencv-python",
    "picamera2",
    "py5",
]
